# -*- coding: utf-8 -*-
"""Correlation_IDH-GDP_France

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwD5YfyiF86C_VegLgmaDLflG3d8hYUP
"""

import pandas as pd
from scipy.stats import pearsonr

from google.colab import drive
drive.mount('/content/drive')

# Carrega o arquivo Excel usando o pandas
caminho_arquivo = '/content/drive/My Drive/Correlação_PIB-IDH_France.xlsx'
dados = pd.read_excel(caminho_arquivo, sheet_name='IDH-PIB')

# Verifica se os dados foram carregados corretamente
print(dados.head())

# Calcula a correlação de Pearson
correlacao, p_valor = pearsonr(dados['Valeurs IDH'], dados['Valeurs PIB'])

# Imprimi a correlação
print(f'Correlação de Pearson: {correlacao}')
print(f'Valor p: {p_valor}')